### ISSUE TITLE
Get odata-connector to work with mule 3.7

### ISSUE THREAD

**Issue by rikvermeer** [mulesoft/odata-connector#3]
The mulesoft odata-connector doesn't work in mule 3.7
http://forums.mulesoft.com/questions/1167/mule-odata-connector.html

The connector has a dependency on jersey 1:

Exception stack is:
1. com.sun.jersey.api.client.filter.Filterable (java.lang.ClassNotFoundException)
  java.net.URLClassLoader:381 (null)
2. com/sun/jersey/api/client/filter/Filterable (java.lang.NoClassDefFoundError)
  org.odata4j.jersey.consumer.ODataJerseyClient:77 (null)
3. com/sun/jersey/api/client/filter/Filterable (java.lang.NoClassDefFoundError). Message payload is of type: NullPayload (org.mule.api.MessagingException)
  org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor:32 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)

I have included jersey 1.19 on the buildpath and it exports to the app library.
Mule says:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ New app 'odatatest'                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-10 15:20:41,207 [main] org.mule.module.launcher.MuleApplicationClassLoader: [odatatest] Loading the following jars:
=============================
file:/Users/rikvermeer/workspace/.mule/apps/odatatest/lib/jersey-bundle-1.19.jar
